python main.py --backbone SAM \
--device_num 2 \
--num_query_position 50 \
--batch_size 4 \
--num_workers 4 \
--epochs 50000 \
--eval_checkpoint_period 5 \
--output_dir anchorSAM_cellpose \
--wandb_run_name anchorSAM_cellpose \
--coco_path /data/AllCellData/dataset/coco/cellpose \
--train_json train_RLE.json \
--val_json val_RLE.json \
--test_json test_RLE.json